import React, { useEffect, useState, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import {
  Video,
  BattleVideo,
  Comment
} from '@/types/video.types';
import VideoPlayer from '@/components/VideoPlayer';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { useAuth } from '@/context/AuthContext';
import { useToast } from "@/components/ui/use-toast";
import { useLiveStreamRealtime } from '@/hooks/useLiveStreamRealtime';
import { useViewerPresence } from '@/hooks/useViewerPresence';
import { useGift } from '@/hooks/useGift';
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { MoreVertical, Send, Heart, MessageSquare, Share2, Gift, Users, Copy, ShieldCheck, Loader2 } from 'lucide-react';
import { Separator } from "@/components/ui/separator"
import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Slider } from "@/components/ui/slider"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { useFollowerRealtime } from '@/hooks/useFollowerRealtime';
import { AspectRatio } from "@/components/ui/aspect-ratio"
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator } from "@/components/ui/command"
import { ScrollArea } from "@/components/ui/scroll-area"

const LiveStreamPage = () => {
  const { videoId } = useParams<{ videoId: string }>();
  const [video, setVideo] = useState<Video | null>(null);
  const [comments, setComments] = useState<Comment[]>([]);
  const [newComment, setNewComment] = useState('');
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isLive, setIsLive] = useState(false);
  const [viewerCount, setViewerCount] = useState(0);
  const [isFollowing, setIsFollowing] = useState(false);
  const [showShareSheet, setShowShareSheet] = useState(false);
  const [volume, setVolume] = useState(50);
  const [isMuted, setIsMuted] = useState(false);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isBattleDialogOpen, setIsBattleDialogOpen] = useState(false);
  const [battleVideos, setBattleVideos] = useState<Video[]>([]);
  const [selectedBattleVideo, setSelectedBattleVideo] = useState<Video | null>(null);
  const [isBattleLoading, setIsBattleLoading] = useState(false);
  const [isBattleRequested, setIsBattleRequested] = useState(false);
  const [isBattleActive, setIsBattleActive] = useState(false);
  const [battleId, setBattleId] = useState<string | null>(null);
  const [battleScore, setBattleScore] = useState({ stream: 0, opponent: 0 });
  const [isBattleEnding, setIsBattleEnding] = useState(false);
  const [isBattleRequestLoading, setIsBattleRequestLoading] = useState(false);
  const [isBattleAcceptLoading, setIsBattleAcceptLoading] = useState(false);
  const [isBattleRejectLoading, setIsBattleRejectLoading] = useState(false);
  const [isBattleEndLoading, setIsBattleEndLoading] = useState(false);
  const [isBattleRequestSent, setIsBattleRequestSent] = useState(false);
  const [isBattleRequestReceived, setIsBattleRequestReceived] = useState(false);
  const [isBattleRequestRejected, setIsBattleRequestRejected] = useState(false);
  const [isBattleRequestAccepted, setIsBattleRequestAccepted] = useState(false);
  const [isBattleEnded, setIsBattleEnded] = useState(false);
  const [isBattleRequestCancelled, setIsBattleRequestCancelled] = useState(false);
  const [isBattleRequestExpired, setIsBattleRequestExpired] = useState(false);
  const [isBattleRequestTimeout, setIsBattleRequestTimeout] = useState(false);
  const [isBattleRequestDeclined, setIsBattleRequestDeclined] = useState(false);
  const [isBattleRequestIgnored, setIsBattleRequestIgnored] = useState(false);
  const [isBattleRequestPending, setIsBattleRequestPending] = useState(false);
  const [isBattleRequestFailed, setIsBattleRequestFailed] = useState(false);
  const [isBattleRequestTimeoutExpired, setIsBattleRequestTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutCancelled, setIsBattleRequestTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutDeclined, setIsBattleRequestTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutIgnored, setIsBattleRequestTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutPending, setIsBattleRequestTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutFailed, setIsBattleRequestTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutExpired] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutCancelled] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutDeclined] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutIgnored] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending, setIsBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutPending] = useState(false);
  const [isBattleRequestTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutTimeoutFailed, setIsBattleRequestTimeoutTimeoutTimeout
